name: Deploy Streamlit App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
          
            APP_DIR=/home/ec2-user/front
            REPO_NAME=Java-springboot-project
            REPO_URL=https://github.com/CloudTechDevOps/Java-springboot-project.git
          
            mkdir -p $APP_DIR
            cd $APP_DIR
          
            if [ -d "$REPO_NAME/.git" ]; then
              cd $REPO_NAME
              git reset --hard
              git pull origin main
            else
              git clone $REPO_URL
              cd $REPO_NAME
            fi
          
            sudo yum install python3-pip -y
          
            cd frontend
          
            # Create venv only if not exists
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
          
            source venv/bin/activate
          
            pip install --upgrade pip
            pip install -r requirements.txt
          
            # Kill old process
            # Kill old process
            pkill -f streamlit || true
            
            # Set API URL
            export API_URL=http://localhost:8084
            
            # 🔥 BEST FIX (detached process)
            setsid bash -c 'source venv/bin/activate && streamlit run app.py --server.port 8501 --server.address 0.0.0.0' > app.log 2>&1 < /dev/null &
            
            sleep 5
            
            echo "✅ Deployment completed"
